development:
  adapter: postgresql
  encoding: UTF8
  database: visa
  pool: 5
  timeout: 5000
  username: visa
  password: password1

test:
  adapter: postgresql
  encoding: UTF8
  database: visatest
  pool: 5
  timeout: 5000
  username: visatest
  password: password1

